name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [force-rebuild]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v4
      
      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Build the project (output to dist/)
      - name: Build
        run: |
          npm run build
          # Verify build output
          ls -la dist/
          ls -la dist/assets/
        env:
          VITE_BASE_URL: ''
      
      # Create 404.html for SPA routing
      - name: Create 404.html
        run: cp dist/index.html dist/404.html

      # Add .nojekyll to prevent Jekyll processing
      - name: Add .nojekyll file
        run: touch dist/.nojekyll

      # Add CNAME for custom domain
      - name: Add CNAME file
        run: echo "thuemecke.net" > dist/CNAME

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # Upload dist/ as artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 